// Test d'intégration Phase 7a : pipeline complet sur les 4 épisodes pilote.
// Read .md → parse → dispatch → LocalZipChannel → vérification du .zip produit.

import AdmZip from 'adm-zip';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { LocalZipChannel } from '../output/channels';
import { FormatDispatcher } from '../output/formats/dispatcher';
import {
  parseBriefAnnexe,
  parseCrossRefs,
  parseKeyMoments,
  parseNewsletter,
  parseQuotes,
} from '../output/parsers/markdownParser';
import type {
  FormatterContext,
  FormatterOutput,
  Livrable,
  ProductionEpisode,
  ProductionPack,
} from '../output/types';
import type { OutputFormatsConfig } from '../output/formats/types';

const ROOT = resolve(
  'experiments',
  'autonomy-session-2026-04-28',
  'pack-pilote-stefani-orso',
);
const EPISODES = [
  { slug: 'plais-platform-sh', displayRef: 'GDIY #266 Frédéric Plais' },
  { slug: 'boissenot-pokemon', displayRef: 'LM #174 Alexandre Boissenot' },
  { slug: 'nooz-optics', displayRef: 'LP #128 Alex Doolaeghe' },
  { slug: 'veyrat-stoik', displayRef: 'GDIY ép. Veyrat (Stoïk)' },
];

const CTX: FormatterContext = {
  clientId: 'stefani-orso',
  clientDisplayName: 'Matthieu Stefani / Orso Media',
  generatedAt: '2026-04-30T18:00:00.000Z',
  brandPrimary: '004CFF',
};

const OUTPUT_FORMATS: OutputFormatsConfig = {
  L1_keyMoments: 'xlsx',
  L2_quotes: 'xlsx',
  L3_crossRefs: 'docx',
  L4_newsletter: 'docx',
  L5_briefAnnexe: 'docx',
};

function buildEpisode(slug: string, displayRef: string): ProductionEpisode {
  const livrables: Livrable[] = [
    parseKeyMoments(readFileSync(resolve(ROOT, slug, '01-key-moments.md'), 'utf-8')),
    parseQuotes(readFileSync(resolve(ROOT, slug, '02-quotes.md'), 'utf-8')),
    parseCrossRefs(readFileSync(resolve(ROOT, slug, '03-cross-refs-by-lens.md'), 'utf-8')),
    parseNewsletter(readFileSync(resolve(ROOT, slug, '04-newsletter.md'), 'utf-8')),
    parseBriefAnnexe(readFileSync(resolve(ROOT, slug, '05-brief-annexe.md'), 'utf-8')),
  ];
  return { slug, displayRef, livrables };
}

describe('output integration — Phase 7a end-to-end', () => {
  it('produces a complete pack zip with 5 files per episode for all 4 pilot episodes', async () => {
    const dispatcher = new FormatDispatcher();
    const episodes = EPISODES.map((e) => buildEpisode(e.slug, e.displayRef));
    const pack: ProductionPack = {
      clientId: CTX.clientId,
      packId: 'phase7a-test',
      generatedAt: CTX.generatedAt,
      episodes,
    };

    const filesByEpisode = new Map<string, FormatterOutput[]>();
    for (const ep of episodes) {
      const outs: FormatterOutput[] = [];
      for (const liv of ep.livrables) {
        outs.push(await dispatcher.dispatch(liv, OUTPUT_FORMATS, CTX));
      }
      filesByEpisode.set(ep.slug, outs);
    }

    const channel = new LocalZipChannel();
    const outDir = resolve('output', 'phase7a-test');
    if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });

    const result = await channel.publish(pack, filesByEpisode, {
      outputDir: outDir,
      readme: '# Phase 7a test — pack pilote\nGenerated by integration test.',
    });

    expect(result.success).toBe(true);
    expect(existsSync(result.location)).toBe(true);

    // Verify zip content
    const zip = new AdmZip(result.location);
    const entries = zip.getEntries().map((e) => e.entryName);
    // 4 episodes × 5 files + README = 21 entries
    expect(entries.length).toBe(21);
    for (const ep of EPISODES) {
      expect(entries).toContain(`${ep.slug}/01-key-moments.xlsx`);
      expect(entries).toContain(`${ep.slug}/02-quotes.xlsx`);
      expect(entries).toContain(`${ep.slug}/03-cross-refs-by-lens.docx`);
      expect(entries).toContain(`${ep.slug}/04-newsletter.docx`);
      expect(entries).toContain(`${ep.slug}/05-brief-annexe.docx`);
    }
    expect(entries).toContain('README.md');

    rmSync(outDir, { recursive: true, force: true });
  });

  it.each(EPISODES)(
    'preserves all key-moment titles in xlsx for $slug',
    async ({ slug }) => {
      const dispatcher = new FormatDispatcher();
      const livrable = parseKeyMoments(
        readFileSync(resolve(ROOT, slug, '01-key-moments.md'), 'utf-8'),
      );
      const out = await dispatcher.dispatch(livrable, OUTPUT_FORMATS, CTX);
      // xlsx is a zip — extract and inspect xl/sharedStrings.xml or sheet1.xml
      const zip = new AdmZip(out.buffer);
      const sheetXml = zip.getEntry('xl/worksheets/sheet1.xml')?.getData().toString('utf-8') ?? '';
      const sharedStringsXml =
        zip.getEntry('xl/sharedStrings.xml')?.getData().toString('utf-8') ?? '';
      const allXml = sheetXml + sharedStringsXml;
      for (const m of livrable.moments) {
        // Le moment titre doit être présent quelque part dans le xlsx
        // (XML escape suffit pour les caractères standard).
        expect(allXml).toContain(escapeXml(m.titre.slice(0, 20)));
      }
    },
  );
});

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
